import { NextResponse } from 'next/server';

export function GET() {
  return NextResponse.json({ openapi: '3.1.0', info: { title: 'BugunBor API', version: '1.0.0-phase1', description: 'Mobile and NFCStore integration boundary. All timestamps are UTC.' }, servers: [{ url: '/api/v1' }], paths: {
    '/deals': { get: { summary: 'List active deals', parameters: [{ name: 'region', in: 'query', schema: { type: 'string' }, description: 'One of the 14 Uzbekistan regions; defaults to Toshkent shahri when no city is given' }, { name: 'city', in: 'query', schema: { type: 'string' }, description: 'A district/city name within the region; when set, overrides the region-wide match' }, { name: 'q', in: 'query', schema: { type: 'string' } }], responses: { '200': { description: 'Active deals' } } } },
    '/deals/{id}/redemptions': { post: { summary: 'Claim an active deal atomically', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }, { name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string', minLength: 12 } }], responses: { '201': { description: 'Claimed' }, '409': { description: 'Expired, sold out, limit, or concurrency conflict' } } } },
    '/businesses': { post: { summary: 'Submit business onboarding (requires acceptedRules: "on")', responses: { '201': { description: 'Pending moderation' }, '401': { description: 'Authentication required' } } } },
    '/business/deals': { post: { summary: 'Submit a new deal for a verified business the caller manages (requires acceptedRules: "on"); rejects a discounted price that is not below the original price', responses: { '201': { description: 'Pending moderation' }, '403': { description: 'No deal.write role on a VERIFIED business' } } } },
    '/business/deals/{id}': { post: { summary: 'Edit a deal: broad edits before it launches, only price-down/quantity-up/end-early once ACTIVE', responses: { '200': { description: 'Updated' }, '409': { description: 'No longer editable, or the change would raise the price / lower stock / extend the deadline' } } } },
    '/business/deals/{id}/cancel': { post: { summary: 'Withdraw a deal before it has ever gone live (soft delete)', responses: { '200': { description: 'Canceled' }, '409': { description: 'Already live or finished — use /stop instead' } } } },
    '/business/deals/{id}/stop': { post: { summary: 'End a live deal immediately', responses: { '200': { description: 'Stopped (status: PAUSED)' } } } },
    '/business/redemptions/validate': { post: { summary: 'Redeem a customer’s one-time code at the branch (code in the JSON body) — the other half of POST /deals/{id}/redemptions', responses: { '200': { description: 'Redeemed' }, '404': { description: 'Code not found for this business' }, '409': { description: 'Already used or expired' } } } },
    '/business/deals/{id}/adjust-stock': { post: { summary: 'Record an in-person sale, decrementing the same remaining_quantity the online claim flow uses', responses: { '200': { description: 'Stock updated' }, '409': { description: 'quantitySold exceeds what remains' } } } },
    '/admin/auth/request-otp': { post: { summary: 'Request an admin login code over Telegram', responses: { '200': { description: 'Code sent if the phone is a registered admin (response is generic either way)' }, '429': { description: 'Rate limited' } } } },
    '/admin/auth/verify-otp': { post: { summary: 'Verify an admin login code and start a session', responses: { '200': { description: 'Session cookie set' }, '401': { description: 'Invalid or expired code' } } } },
    '/admin/deals/{id}/decision': { post: { summary: 'Approve or reject a deal with a required reason', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Decision recorded and audited' }, '403': { description: 'Admin session with deal-moderation permission required' } } } },
    '/admin/businesses/{id}/decision': { post: { summary: 'Verify, reject, suspend or reinstate a business', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Decision recorded and audited' } } } },
    '/admin/businesses/{id}/plan': { post: { summary: 'Assign a business to a pricing plan and subscription status', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Plan assignment recorded and audited' } } } },
    '/admin/plans/{id}': { post: { summary: 'Update a pricing plan (price, features, active state)', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Plan updated' } } } },
    '/admin/deals/{id}/sponsor': { post: { summary: 'Toggle sponsored (top-of-search) placement for a deal — only allowed when its business is on an active Pro plan', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Sponsorship updated' }, '409': { description: 'Business is not on an active Pro plan' } } } },
    '/admin/announcements': { post: { summary: 'Post a message (optionally templated from an active deal) to the Telegram announcement channel', security: [{ adminSessionCookie: [] }], responses: { '201': { description: 'Posted and logged' }, '502': { description: 'Telegram delivery failed' } } } },
    '/admin/team': { post: { summary: 'Invite a new admin/manager/accountant account', security: [{ adminSessionCookie: [] }], responses: { '201': { description: 'Admin account created' }, '403': { description: 'SUPER_ADMIN role required' } } } },
    '/admin/team/{id}': { post: { summary: 'Update an admin account (role, status, Telegram chat id)', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Admin account updated' }, '403': { description: 'SUPER_ADMIN role required' } } } },
    '/favorites': { post: { summary: 'Toggle a deal in/out of the caller\'s saved list', security: [{ sessionCookie: [] }], responses: { '200': { description: 'Toggled — response says which way' }, '401': { description: 'Authentication required' } } } },
    '/reviews': { post: { summary: 'Rate a business (1-5) with an optional comment, tied to a COMPLETED redemption the caller owns — one review per redemption', security: [{ sessionCookie: [] }], responses: { '201': { description: 'Review recorded' }, '409': { description: 'Redemption not completed yet, or already reviewed' } } } },
    '/support/tickets': { post: { summary: 'Submit a support/contact request (name, phone, subject, message) — used by the contact form and the AI Yordamchi lead-capture gate', responses: { '201': { description: 'Ticket created' }, '422': { description: 'Missing or invalid field' } } } },
    '/admin/support/{id}': { post: { summary: 'Update a support ticket’s status and resolution note', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Ticket updated' }, '403': { description: 'Admin session with admin.support.manage permission required' } } } },
  }, components: { securitySchemes: {
    sessionCookie: { type: 'apiKey', in: 'cookie', name: '__Host-bugunbor_session' },
    adminSessionCookie: { type: 'apiKey', in: 'cookie', name: 'bb_admin_session' },
  } } });
}
