import { NextResponse } from 'next/server';

export function GET() {
  return NextResponse.json({ openapi: '3.1.0', info: { title: 'BugunBor API', version: '1.0.0-phase1', description: 'Mobile and NFCStore integration boundary. All timestamps are UTC.' }, servers: [{ url: '/api/v1' }], paths: {
    '/deals': { get: { summary: 'List active deals', parameters: [{ name: 'region', in: 'query', schema: { type: 'string' }, description: 'One of the 14 Uzbekistan regions; defaults to Toshkent shahri when no city is given' }, { name: 'city', in: 'query', schema: { type: 'string' }, description: 'A district/city name within the region; when set, overrides the region-wide match' }, { name: 'q', in: 'query', schema: { type: 'string' } }], responses: { '200': { description: 'Active deals' } } } },
    '/deals/{id}/redemptions': { post: { summary: 'Claim an active deal atomically; body may include a promoCode applied on top of the deal price and/or a timeSlotId to book a SERVICE deal\'s slot', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }, { name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string', minLength: 12 } }], responses: { '201': { description: 'Claimed' }, '409': { description: 'Expired, sold out, limit, promo-code, slot, or concurrency conflict' }, '422': { description: 'Promo code or time slot not found' } } } },
    '/businesses': { post: { summary: 'Submit business onboarding (requires acceptedRules: "on")', responses: { '201': { description: 'Pending moderation' }, '401': { description: 'Authentication required' } } } },
    '/business/deals': { post: { summary: 'Submit a new deal for a verified business the caller manages (requires acceptedRules: "on"); rejects a discounted price that is not below the original price; optional listingType (PRODUCT/SERVICE), autoDiscountTiers (Auto Skidka), and timeSlots (SERVICE bookings)', responses: { '201': { description: 'Pending moderation' }, '403': { description: 'No deal.write role on a VERIFIED business' } } } },
    '/business/deals/{id}': { post: { summary: 'Edit a deal: broad edits before it launches, only price-down/quantity-up/end-early once ACTIVE', responses: { '200': { description: 'Updated' }, '409': { description: 'No longer editable, or the change would raise the price / lower stock / extend the deadline' } } } },
    '/business/deals/{id}/cancel': { post: { summary: 'Withdraw a deal before it has ever gone live (soft delete)', responses: { '200': { description: 'Canceled' }, '409': { description: 'Already live or finished — use /stop instead' } } } },
    '/business/deals/{id}/stop': { post: { summary: 'End a live deal immediately', responses: { '200': { description: 'Stopped (status: PAUSED)' } } } },
    '/business/redemptions/validate': { post: { summary: 'Redeem a customer’s one-time code at the branch (code in the JSON body) — the other half of POST /deals/{id}/redemptions', responses: { '200': { description: 'Redeemed' }, '404': { description: 'Code not found for this business' }, '409': { description: 'Already used or expired' } } } },
    '/business/deals/{id}/adjust-stock': { post: { summary: 'Record an in-person sale, decrementing the same remaining_quantity the online claim flow uses', responses: { '200': { description: 'Stock updated' }, '409': { description: 'quantitySold exceeds what remains' } } } },
    '/auth/otp/request': { post: { summary: 'Request a customer/business login code over Telegram; a first-time phone gets the bot\'s own link to open instead (Telegram can\'t message a chat that hasn\'t messaged it first) — opening it and sharing a phone number via the bot\'s "share phone number" button, then calling this again, sends the actual code', responses: { '200': { description: '{status: "SENT"} or {status: "NEEDS_TELEGRAM_LINK", telegramDeepLink}' }, '429': { description: 'Rate limited (max 3 codes / 10 min)' } } } },
    '/auth/otp/verify': { post: { summary: 'Verify a customer/business login code and start a session', responses: { '200': { description: 'Session cookie set' }, '401': { description: 'Invalid or expired code' }, '429': { description: 'Too many wrong attempts' } } } },
    '/auth/logout': { post: { summary: 'Revoke the caller\'s session and clear its cookie', security: [{ sessionCookie: [] }], responses: { '200': { description: 'Logged out' } } } },
    '/telegram/bot/webhook': { post: { summary: 'Telegram calls this on every bot message; on /start it offers a native "share phone number" button, and on the resulting contact message it pairs that chat with the shared phone number', responses: { '200': { description: 'Always — Telegram retries indefinitely on anything else' }, '401': { description: 'secret_token header did not match' }, '503': { description: 'No webhook secret configured' } } } },
    '/admin/auth/request-otp': { post: { summary: 'Request an admin login code over Telegram', responses: { '200': { description: 'Code sent if the phone is a registered admin (response is generic either way)' }, '429': { description: 'Rate limited' } } } },
    '/admin/auth/verify-otp': { post: { summary: 'Verify an admin login code and start a session', responses: { '200': { description: 'Session cookie set' }, '401': { description: 'Invalid or expired code' } } } },
    '/admin/deals/{id}/decision': { post: { summary: 'Approve or reject a deal with a required reason', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Decision recorded and audited' }, '403': { description: 'Admin session with deal-moderation permission required' } } } },
    '/admin/businesses/{id}/decision': { post: { summary: 'Verify, reject, suspend or reinstate a business', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Decision recorded and audited' } } } },
    '/admin/businesses/{id}/plan': { post: { summary: 'Assign a business to a pricing plan and subscription status', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Plan assignment recorded and audited' } } } },
    '/admin/plans/{id}': { post: { summary: 'Update a pricing plan (price, features, active state)', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Plan updated' } } } },
    '/admin/deals/{id}/sponsor': { post: { summary: 'Toggle sponsored (top-of-search) placement for a deal — only allowed when its business is on an active Pro plan', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Sponsorship updated' }, '409': { description: 'Business is not on an active Pro plan' } } } },
    '/admin/announcements': { post: { summary: 'Post a message (optionally templated from an active deal) to the Telegram announcement channel', security: [{ adminSessionCookie: [] }], responses: { '201': { description: 'Posted and logged' }, '502': { description: 'Telegram delivery failed' } } } },
    '/admin/team': { post: { summary: 'Invite a new admin/manager/accountant account', security: [{ adminSessionCookie: [] }], responses: { '201': { description: 'Admin account created' }, '403': { description: 'SUPER_ADMIN role required' } } } },
    '/admin/team/{id}': { post: { summary: 'Update an admin account (role, status, Telegram chat id)', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Admin account updated' }, '403': { description: 'SUPER_ADMIN role required' } } } },
    '/admin/promo-codes': { post: { summary: 'Create a promo code (PERCENT or FIXED discount, optional max uses and expiry)', security: [{ adminSessionCookie: [] }], responses: { '201': { description: 'Promo code created' }, '409': { description: 'Code already exists' } } } },
    '/admin/promo-codes/{id}': { post: { summary: 'Toggle a promo code active/inactive', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Updated' }, '404': { description: 'Promo code not found' } } } },
    '/telegram/webapp/auth': { post: { summary: 'Verify Telegram Mini App initData and start a marketplace session for that Telegram user', responses: { '200': { description: 'Session cookie set' }, '401': { description: 'initData failed HMAC verification or is stale' }, '503': { description: 'No bot token configured' } } } },
    '/favorites': { post: { summary: 'Toggle a deal in/out of the caller\'s saved list', security: [{ sessionCookie: [] }], responses: { '200': { description: 'Toggled — response says which way' }, '401': { description: 'Authentication required' } } } },
    '/reviews': { post: { summary: 'Rate a business (1-5) with an optional comment, tied to a COMPLETED redemption the caller owns — one review per redemption', security: [{ sessionCookie: [] }], responses: { '201': { description: 'Review recorded' }, '409': { description: 'Redemption not completed yet, or already reviewed' } } } },
    '/support/tickets': { post: { summary: 'Submit a support/contact request (name, phone, subject, message) — used by the contact form and the AI Yordamchi lead-capture gate', responses: { '201': { description: 'Ticket created' }, '422': { description: 'Missing or invalid field' } } } },
    '/admin/support/{id}': { post: { summary: 'Update a support ticket’s status and resolution note', security: [{ adminSessionCookie: [] }], responses: { '200': { description: 'Ticket updated' }, '403': { description: 'Admin session with admin.support.manage permission required' } } } },
  }, components: { securitySchemes: {
    sessionCookie: { type: 'apiKey', in: 'cookie', name: '__Host-bugunbor_session' },
    adminSessionCookie: { type: 'apiKey', in: 'cookie', name: 'bb_admin_session' },
  } } });
}
