/// English texts for the server's error codes. The server answers in Uzbek or
/// Russian (lib/i18n on the site); an app set to English shows these instead.
/// Codes the app words itself (network, sign-in, not found, too many tries,
/// server) and admin-only ones are not here.
const englishErrors = <String, String>{
  'FORBIDDEN': 'You don’t have permission to do this.',
  'VALIDATION': 'Please check the details.',
  'CONFLICT': 'Something has changed. Please refresh.',
  'INVALID_TRANSITION': 'This can’t be done right now.',
  'DEAL_NOT_ACTIVE': 'This deal isn’t active right now.',
  'DEAL_NOT_STARTED': 'This deal hasn’t started yet.',
  'DEAL_EXPIRED': 'This deal has ended.',
  'SOLD_OUT': 'Sorry, this deal is sold out.',
  'LIMIT_REACHED': 'You’ve already used this deal as many times as allowed.',
  'ALREADY_CLAIMED': 'You already have an active code for this deal.',
  'DEMO_DEAL': 'This is a sample deal: it can’t be booked.',
  'BRANCH_UNAVAILABLE': 'This deal isn’t valid at the chosen branch.',
  'BUSINESS_UNAVAILABLE': 'This business isn’t active right now.',
  'BUSINESS_NOT_VERIFIED': 'This business hasn’t been approved yet.',
  'CODE_NOT_FOUND': 'Code not found, or it belongs to another business.',
  'CODE_EXPIRED': 'This code has expired.',
  'CODE_USED': 'This code has already been used.',
  'CODE_CANCELED': 'This code was cancelled.',
  'TELEGRAM_NOT_CONFIGURED': 'Signing in with Telegram isn’t available yet.',
  'LOGIN_EXPIRED': 'The sign-in request has expired. Please try again.',
  'ACCOUNT_BLOCKED': 'Your account is blocked.',
  'SOLE_OWNER': 'You’re the only owner of a business. Add another owner to the team, or close the business, then delete your account.',
  'CONSENT_REQUIRED': 'To continue, agree to the privacy policy and the terms of use.',
  'USER_NOT_FOUND': 'No one with this number. The employee should first sign in to BugunBor with Telegram.',
  'ALREADY_MEMBER': 'This person is already on the team.',
  'LAST_BRANCH': 'At least one branch has to stay.',
  'BRANCH_IN_USE': 'This branch has a live deal or one in review.',
  'SELF_ACTION': 'You can’t do this to yourself.',
  'SUBSCRIPTION_EXPIRED': 'The free period or plan has ended. Choose a plan to continue.',
  'TARIFFS_OFF': 'There are no plans yet — BugunBor is free for businesses.',
  'PAYMENTS_DISABLED': 'Payments are made on the website.',
  'PLAN_LIMIT': 'You’ve reached your plan’s limit. Move to a bigger plan.',
  'END_IN_PAST': 'The end time has already passed. Please change it.',
  'NO_BRANCH': 'The deal has no branch left. Open it and choose at least one branch.',
  'BUSINESS_LIMIT': 'One account can add at most 5 businesses.',
  'IMAGE_TOO_LARGE': 'The picture is too large. Choose another one.',
  'MEDIA_LIMIT': 'Too many photos were uploaded today. Try again tomorrow.',
  'REVIEW_NOT_ALLOWED': 'Only used codes can be rated, within 30 days.',
  'ALREADY_REVIEWED': 'This visit has already been rated.',
  'IMAGE_INVALID': 'This file isn’t a picture, or its format isn’t supported (JPG, PNG, WebP).',
  'ISSUE_TOO_LATE': 'A complaint about a code can be sent within 3 days of booking it.',
  'UNDER_REVIEW': 'This deal is being checked after complaints. A moderator will turn it back on.',
  'NO_SHOW_PAUSE': '3 codes went unused in the last 7 days, so booking is paused for now.',
};
