// Generated by scripts/fetch-stock-photos.mjs: freely licensed original photos
// (Wikimedia Commons) keyed by deal visual, shown only on demo deals.
// Regenerate with the script instead of editing by hand.

export type StockPhoto = { src: string; title: string; author: string; license: string; licenseUrl: string; source: string };

export const STOCK_PHOTOS: Record<string, StockPhoto> = {};
