// Generated by scripts/fetch-stock-photos.mjs and scripts/import-photos.mjs:
// freely licensed original photos keyed by deal visual ("plov-2" is a second
// photo of plov), shown only on demo deals. /credits lists the authors.
// Regenerate with the scripts instead of editing by hand.

export type StockPhoto = { src: string; title: string; author: string; license: string; licenseUrl: string; source: string };

export const STOCK_PHOTOS: Record<string, StockPhoto> = {
  "backpack": {
    "src": "/photos/backpack.webp",
    "title": "Boy-in-brown-hoodie-carrying-red-backpack-while-walking-on-207697",
    "author": "ambermb",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Boy-in-brown-hoodie-carrying-red-backpack-while-walking-on-207697.jpg"
  },
  "barber": {
    "src": "/photos/barber.webp",
    "title": "Barbershop in Cancun",
    "author": "Ekaterina Kvelidze",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Barbershop_in_Cancun.jpg"
  },
  "beauty": {
    "src": "/photos/beauty.webp",
    "title": "French Manicure with Glitter nail art on ring finger",
    "author": "Theknowhau",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:French_Manicure_with_Glitter_nail_art_on_ring_finger.jpg"
  },
  "billiards": {
    "src": "/photos/billiards.webp",
    "title": "Billiards table 2",
    "author": "MarkBuckawicki",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Billiards_table_2.JPG"
  },
  "books": {
    "src": "/photos/books.webp",
    "title": "Bookstore shelves",
    "author": "Punker1999",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Bookstore_shelves.jpg"
  },
  "bowling": {
    "src": "/photos/bowling.webp",
    "title": "Bowland Elizabeth, Edinburgh North 20251209-093756",
    "author": "RegionVisitor90",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Bowland_Elizabeth,_Edinburgh_North_20251209-093756.jpg"
  },
  "boxing": {
    "src": "/photos/boxing.webp",
    "title": "Boxing gloves Bail 10-OZ (4)",
    "author": "Sevela.p",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Boxing_gloves_Bail_10-OZ_(4).jpg"
  },
  "bread": {
    "src": "/photos/bread.webp",
    "title": "Uzbekistan lives of citizens IGP3003",
    "author": "w0zny",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Uzbekistan_lives_of_citizens_IGP3003.jpg"
  },
  "breakfast": {
    "src": "/photos/breakfast.webp",
    "title": "Omelette 20210505 075028",
    "author": "Ka23 13",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Omelette_20210505_075028.jpg"
  },
  "burger": {
    "src": "/photos/burger.webp",
    "title": "Homemade hamburger with french fries in Argentina",
    "author": "Horacio Cambeiro",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Homemade_hamburger_with_french_fries_in_Argentina.jpg"
  },
  "cake": {
    "src": "/photos/cake.webp",
    "title": "Piece of chocolate cake on a white plate decorated with chocolate sauce",
    "author": "Daria Yakovleva",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Piece_of_chocolate_cake_on_a_white_plate_decorated_with_chocolate_sauce.jpg"
  },
  "camera": {
    "src": "/photos/camera.webp",
    "title": "2018-Pulitzer-Prizes-photo-studio",
    "author": "Fuzheado",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:2018-Pulitzer-Prizes-photo-studio.jpg"
  },
  "car": {
    "src": "/photos/car.webp",
    "title": "2015 Kłodzko, ul. Dusznicka, myjnia samochodowa 02",
    "author": "Jacek Halicki",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:2015_K%C5%82odzko,_ul._Dusznicka,_myjnia_samochodowa_02.jpg"
  },
  "chicken": {
    "src": "/photos/chicken.webp",
    "title": "Chicken Tandoori 01",
    "author": "Marajozkee",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chicken_Tandoori_01.jpg"
  },
  "chicken-2": {
    "src": "/photos/chicken-2.webp",
    "title": "Tandoori Chicken Home Made",
    "author": "Suchitra08",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tandoori_Chicken_Home_Made.JPG"
  },
  "cinema": {
    "src": "/photos/cinema.webp",
    "title": "Columbia City Cinema main hall",
    "author": "Joe Mabel",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Columbia_City_Cinema_main_hall.jpg"
  },
  "cleaning": {
    "src": "/photos/cleaning.webp",
    "title": "Spray cleaner",
    "author": "BEtech4856",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Spray_cleaner.jpg"
  },
  "clothes": {
    "src": "/photos/clothes.webp",
    "title": "Interior sports clothing store Cala Millor",
    "author": "Steffen Mokosch",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Interior_sports_clothing_store_Cala_Millor.jpg"
  },
  "coffee": {
    "src": "/photos/coffee.webp",
    "title": "Classical Cappuccino in Savour Cafe",
    "author": "Peachyeung316",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Classical_Cappuccino_in_Savour_Cafe.jpg"
  },
  "coffee-2": {
    "src": "/photos/coffee-2.webp",
    "title": "A-cup-of-cappuccino-coffee-dar-es-salaam-cafe",
    "author": "Aneth David (SLU)",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:A-cup-of-cappuccino-coffee-dar-es-salaam-cafe.jpg"
  },
  "computer": {
    "src": "/photos/computer.webp",
    "title": "Computer Lab Baraboo",
    "author": "JackFromWisconsin",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Computer_Lab_Baraboo.jpg"
  },
  "crafts": {
    "src": "/photos/crafts.webp",
    "title": "Piyola-choynak 1",
    "author": "Xkmvch",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Piyola-choynak_1.jpg"
  },
  "delivery": {
    "src": "/photos/delivery.webp",
    "title": "Food delivery by scooter in France (1)",
    "author": "Cjp24",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Food_delivery_by_scooter_in_France_(1).jpg"
  },
  "dessert": {
    "src": "/photos/dessert.webp",
    "title": "Cheshire cupcakes",
    "author": "Katjaskupcakes katja Seaton",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cheshire_cupcakes.jpg"
  },
  "doll": {
    "src": "/photos/doll.webp",
    "title": "224 Molí paperer Meros (Konigil, Samarcanda), ninos",
    "author": "Enric",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:224_Mol%C3%AD_paperer_Meros_(Konigil,_Samarcanda),_ninos.jpg"
  },
  "doppi": {
    "src": "/photos/doppi.webp",
    "title": "Tajik Tubeteika-2",
    "author": "Eugene Zelenko",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tajik_Tubeteika-2.jpg"
  },
  "dumplings": {
    "src": "/photos/dumplings.webp",
    "title": "Uzbek Manti (bright)",
    "author": "Ramón from Llanera, España ; brightened by Off-shell",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Uzbek_Manti_(bright).jpg"
  },
  "education": {
    "src": "/photos/education.webp",
    "title": "Classroom in Foreign Languages Building - Tunghai University- DSC01517",
    "author": "Daderot",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Classroom_in_Foreign_Languages_Building_-_Tunghai_University-_DSC01517.JPG"
  },
  "fabric": {
    "src": "/photos/fabric.webp",
    "title": "Adras (Ikat). 1990s. Silk, cotton",
    "author": "Panpanchik",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Adras_(Ikat)._1990s._Silk,_cotton.jpg"
  },
  "fabric-2": {
    "src": "/photos/fabric-2.webp",
    "title": "Adras (Ikat). 1990s. Silk, cotton (3)",
    "author": "Panpanchik",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Adras_(Ikat)._1990s._Silk,_cotton_(3).jpg"
  },
  "facial": {
    "src": "/photos/facial.webp",
    "title": "Routine Facial Treatment And Care",
    "author": "Davidbrenna.artist",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Routine_Facial_Treatment_And_Care.jpg"
  },
  "fitness": {
    "src": "/photos/fitness.webp",
    "title": "Colorful pile of dumbbells at the gym 2",
    "author": "Ser Amantio di Nicolao",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Colorful_pile_of_dumbbells_at_the_gym_2.jpg"
  },
  "flowers": {
    "src": "/photos/flowers.webp",
    "title": "Bouquet de roses roses",
    "author": "Jebulon",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bouquet_de_roses_roses.jpg"
  },
  "football": {
    "src": "/photos/football.webp",
    "title": "Futsal indoor",
    "author": "Christopherjeffrey04",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Futsal_indoor.jpg"
  },
  "fruit": {
    "src": "/photos/fruit.webp",
    "title": "A basket of fruits",
    "author": "Suyash Dwivedi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:A_basket_of_fruits.jpg"
  },
  "fun": {
    "src": "/photos/fun.webp",
    "title": "Illuminated Ferris wheel, bouncing castle and carousel at night in a funfair in Vientiane, Laos",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Illuminated_Ferris_wheel,_bouncing_castle_and_carousel_at_night_in_a_funfair_in_Vientiane,_Laos.jpg"
  },
  "game": {
    "src": "/photos/game.webp",
    "title": "KontrolerDualSense",
    "author": "Xephuwu",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:KontrolerDualSense.jpg"
  },
  "gift": {
    "src": "/photos/gift.webp",
    "title": "Brown gift box with red ribbon and bow",
    "author": "Shixart1985",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Brown_gift_box_with_red_ribbon_and_bow.jpg"
  },
  "hair": {
    "src": "/photos/hair.webp",
    "title": "Cutting hair - haircuts",
    "author": "geehairimages",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cutting_hair_-_haircuts.jpg"
  },
  "horse": {
    "src": "/photos/horse.webp",
    "title": "Horseback Riding on Limberlost Trail (51832760724)",
    "author": "ShenandoahNPS",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Licensing",
    "source": "https://commons.wikimedia.org/wiki/File:Horseback_Riding_on_Limberlost_Trail_(51832760724).jpg"
  },
  "icecream": {
    "src": "/photos/icecream.webp",
    "title": "Ice Cream Trio @ Maid of Auckland Hotel, Edwardstown 20250314-124805",
    "author": "RegionVisitor90",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Ice_Cream_Trio_@_Maid_of_Auckland_Hotel,_Edwardstown_20250314-124805.jpg"
  },
  "karaoke": {
    "src": "/photos/karaoke.webp",
    "title": "Karaoke in Nha Trang",
    "author": "Christophe95",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Karaoke_in_Nha_Trang.jpg"
  },
  "kids": {
    "src": "/photos/kids.webp",
    "title": "Ball pit with playground slide",
    "author": "Rachmaninoff",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ball_pit_with_playground_slide.jpg"
  },
  "kitchen": {
    "src": "/photos/kitchen.webp",
    "title": "Saucepan",
    "author": "Donovan Govan.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Saucepan.jpg"
  },
  "kurash": {
    "src": "/photos/kurash.webp",
    "title": "Tournoi de Kurash 27",
    "author": "Kani Beat",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Tournoi_de_Kurash_27.jpg"
  },
  "laptop": {
    "src": "/photos/laptop.webp",
    "title": "Thermal CompoundApplying",
    "author": "Jyothis at ml.wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Thermal_CompoundApplying.JPG"
  },
  "laundry": {
    "src": "/photos/laundry.webp",
    "title": "Dry cleaned clothes (Unsplash)",
    "author": "m0851 m0851",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Dry_cleaned_clothes_(Unsplash).jpg"
  },
  "lunch": {
    "src": "/photos/lunch.webp",
    "title": "EM Main course (3627263529)",
    "author": "Eddie Maloney from North Las Vegas, USA",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:EM_Main_course_(3627263529).jpg"
  },
  "lunch-2": {
    "src": "/photos/lunch-2.webp",
    "title": "Buffet lunch at restaurant Sapusca in December 2023",
    "author": "JIP",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Buffet_lunch_at_restaurant_Sapusca_in_December_2023.jpg"
  },
  "makeup": {
    "src": "/photos/makeup.webp",
    "title": "2012-11-19 Eyelash extensions at the Shilin Night Market",
    "author": "Maya-Anaïs Y.",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:2012-11-19_Eyelash_extensions_at_the_Shilin_Night_Market.jpg"
  },
  "meat": {
    "src": "/photos/meat.webp",
    "title": "Qozon kabob (Uzbek national cuisine)",
    "author": "Shuhrataxmedov",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Qozon_kabob_(Uzbek_national_cuisine).jpg"
  },
  "noodles": {
    "src": "/photos/noodles.webp",
    "title": "Uzbek lagman",
    "author": "赤猫法師",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Uzbek_lagman.jpg"
  },
  "nuts": {
    "src": "/photos/nuts.webp",
    "title": "Mercado de Chorsu 05",
    "author": "LBM1948",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mercado_de_Chorsu_05.jpg"
  },
  "nuts-2": {
    "src": "/photos/nuts-2.webp",
    "title": "Samarcanda, Siyab 5",
    "author": "LBM1948",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samarcanda,_Siyab_5.jpg"
  },
  "phone": {
    "src": "/photos/phone.webp",
    "title": "Smartphone with case cover on table",
    "author": "Santeri Viinamäki",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Smartphone_with_case_cover_on_table.jpg"
  },
  "pizza": {
    "src": "/photos/pizza.webp",
    "title": "Margherita Originale",
    "author": "Mario56",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Margherita_Originale.JPG"
  },
  "plov": {
    "src": "/photos/plov.webp",
    "title": "Plov with lamb and carrots in ceramic bowl",
    "author": "Postovalov",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Plov_with_lamb_and_carrots_in_ceramic_bowl.jpg"
  },
  "plov-2": {
    "src": "/photos/plov-2.webp",
    "title": "Urazmat-Plov",
    "author": "Ji-Elle",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Urazmat-Plov.jpg"
  },
  "plov-3": {
    "src": "/photos/plov-3.webp",
    "title": "Uzbekistan style plov in Japan",
    "author": "赤猫法師",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Uzbekistan_style_plov_in_Japan.jpg"
  },
  "pool": {
    "src": "/photos/pool.webp",
    "title": "Swimming Pool lanes and starting blocks",
    "author": "KeepActive Australia from Melbourne, VIC, Australia",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Swimming_Pool_lanes_and_starting_blocks.jpg"
  },
  "quest": {
    "src": "/photos/quest.webp",
    "title": "Escape Room - \"The Expedition\" (Escape Quest Bethesda)",
    "author": "Hudson Bloom",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Escape_Room_-_%22The_Expedition%22_(Escape_Quest_Bethesda).jpg"
  },
  "repair": {
    "src": "/photos/repair.webp",
    "title": "Modern split-type air conditioner at a school",
    "author": "Curpharar",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Modern_split-type_air_conditioner_at_a_school.jpg"
  },
  "samsa": {
    "src": "/photos/samsa.webp",
    "title": "Uzbek samsa in Vienna, Austria",
    "author": "Nurken",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Uzbek_samsa_in_Vienna,_Austria.jpg"
  },
  "samsa-2": {
    "src": "/photos/samsa-2.webp",
    "title": "Samsa of Khiva",
    "author": "Davide Mauro",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsa_of_Khiva.jpg"
  },
  "samsa-3": {
    "src": "/photos/samsa-3.webp",
    "title": "'Parmuda'-uzbek samsa-02",
    "author": "Shuhrataxmedov",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:%27Parmuda%27-uzbek_samsa-02.jpg"
  },
  "sewing": {
    "src": "/photos/sewing.webp",
    "title": "Woman sewing a face mask with a Singer machine 14",
    "author": "Tadeáš Bednarz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Woman_sewing_a_face_mask_with_a_Singer_machine_14.jpg"
  },
  "shashlik": {
    "src": "/photos/shashlik.webp",
    "title": "Shashlik-national food of Uzbekistan",
    "author": "Muharramxon",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Shashlik-national_food_of_Uzbekistan.jpg"
  },
  "shoes": {
    "src": "/photos/shoes.webp",
    "title": "Swanson Shoe Repair 04A",
    "author": "Joe Mabel",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:Swanson_Shoe_Repair_04A.jpg"
  },
  "shopping": {
    "src": "/photos/shopping.webp",
    "title": "Siyob Bazaar in Samarkand 3",
    "author": "Adam Harangozó",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Siyob_Bazaar_in_Samarkand_3.jpg"
  },
  "sneakers": {
    "src": "/photos/sneakers.webp",
    "title": "Converse Jack Purcell sneakers on white canvas",
    "author": "Mizael Contreras",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Converse_Jack_Purcell_sneakers_on_white_canvas.jpg"
  },
  "soup": {
    "src": "/photos/soup.webp",
    "title": "Суп Мастава",
    "author": "Olexdj",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:%D0%A1%D1%83%D0%BF_%D0%9C%D0%B0%D1%81%D1%82%D0%B0%D0%B2%D0%B0.jpg"
  },
  "spa": {
    "src": "/photos/spa.webp",
    "title": "Ostentrop Germany Chanchai-Thaimassage-10",
    "author": "CEphoto, Uwe Aranas",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ostentrop_Germany_Chanchai-Thaimassage-10.jpg"
  },
  "spa-2": {
    "src": "/photos/spa-2.webp",
    "title": "YHI Spa treatment room at Paradisus by Meliá Bali",
    "author": "Paradisus Bali",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:YHI_Spa_treatment_room_at_Paradisus_by_Meli%C3%A1_Bali.jpg"
  },
  "sushi": {
    "src": "/photos/sushi.webp",
    "title": "Sushi at Luckiefun's in November 2023",
    "author": "JIP",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sushi_at_Luckiefun%27s_in_November_2023.jpg"
  },
  "suzani": {
    "src": "/photos/suzani.webp",
    "title": "Boukhara-Suzani (2)",
    "author": "Ji-Elle",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Boukhara-Suzani_(2).jpg"
  },
  "sweets": {
    "src": "/photos/sweets.webp",
    "title": "Люблю сладости это элемент гостеприимства",
    "author": "Ташова Ширин",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%D0%9B%D1%8E%D0%B1%D0%BB%D1%8E_%D1%81%D0%BB%D0%B0%D0%B4%D0%BE%D1%81%D1%82%D0%B8_%D1%8D%D1%82%D0%BE_%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82_%D0%B3%D0%BE%D1%81%D1%82%D0%B5%D0%BF%D1%80%D0%B8%D0%B8%D0%BC%D1%81%D1%82%D0%B2%D0%B0.jpg"
  },
  "tea": {
    "src": "/photos/tea.webp",
    "title": "Uzbek tea couple with traditional coloration",
    "author": "Ekaterina Kvelidze",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Uzbek_tea_couple_with_traditional_coloration.jpg"
  },
  "tennis": {
    "src": "/photos/tennis.webp",
    "title": "Pörtschach Johannes-Brahms-Promenade Werzer-Tennis-Arena 27052017 8932",
    "author": "Johann Jaritz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:P%C3%B6rtschach_Johannes-Brahms-Promenade_Werzer-Tennis-Arena_27052017_8932.jpg"
  },
  "theater": {
    "src": "/photos/theater.webp",
    "title": "Küçük Tiyatro",
    "author": "Gargarapalvin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:K%C3%BC%C3%A7%C3%BCk_Tiyatro.jpg"
  },
  "tires": {
    "src": "/photos/tires.webp",
    "title": "Tire Changer",
    "author": "Flippin504",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tire_Changer.jpg"
  },
  "water": {
    "src": "/photos/water.webp",
    "title": "Water bottles in yuen long",
    "author": "Peachyeung316",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Water_bottles_in_yuen_long.jpg"
  },
  "woodcarving": {
    "src": "/photos/woodcarving.webp",
    "title": "Djouma mosque column detail 2",
    "author": "Faqscl",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Djouma_mosque_column_detail_2.JPG"
  },
  "woodcarving-2": {
    "src": "/photos/woodcarving-2.webp",
    "title": "Artisanat et tourisme (Khiva, Ouzbékistan) (5606264361)",
    "author": "Jean-Pierre Dalbéra from Paris, France",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Artisanat_et_tourisme_(Khiva,_Ouzb%C3%A9kistan)_(5606264361).jpg"
  },
  "wrap": {
    "src": "/photos/wrap.webp",
    "title": "Shawarma Sandwich",
    "author": "Siqbal at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Shawarma_Sandwich.jpg"
  },
  "yoga": {
    "src": "/photos/yoga.webp",
    "title": "Girl doing bird dog yoga pose 2",
    "author": "PTPioneer",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Girl_doing_bird_dog_yoga_pose_2.jpg"
  }
};
