// Russian for the texts of the sample (demo) catalogue, keyed by the Uzbek
// text the seed writes: deal titles, descriptions and terms, what sets hold,
// business descriptions and branch names. The Russian site shows samples in
// Russian (modules/catalog/queries.ts); businesses' own texts are never
// translated. db/demo-ru.test.ts checks that every sample text has its line.

const TITLES: Array<[string, string]> = [
  // Showcase businesses (db/seed.ts).
  ['To‘y oshi va achchiq-chuchuk', 'Свадебный плов и ачик-чучук'],
  ['Butun tortlar kechki narxda', 'Целые торты по вечерней цене'],
  ['Biznes kitoblar to‘plami', 'Набор книг о бизнесе'],
  ['Lag‘mon va salat kombo', 'Комбо: лагман и салат'],
  ['Ertalabki kofe + kruassan', 'Утренний кофе + круассан'],
  ['Kechki desert seti', 'Вечерний десертный сет'],
  ['Manikyur 30% chegirma bilan', 'Маникюр со скидкой 30%'],
  ['Bir martalik mashg‘ulot yarim narxda', 'Разовая тренировка за полцены'],
  ['Oilaviy osh seti', 'Семейный сет с пловом'],
  // Food.
  ['To‘y oshi + salat + non', 'Свадебный плов + салат + лепёшка'],
  ['Qo‘lda cho‘zilgan lag‘mon + choy', 'Лагман ручной тяжки + чай'],
  ['Shashlik seti: 5 six + non + piyoz', 'Шашлычный сет: 5 шампуров + лепёшка + лук'],
  ['Bug‘da pishgan manti (5 dona)', 'Манты на пару (5 шт.)'],
  ['3 ta tandir somsa + ko‘k choy', '3 тандырные самсы + зелёный чай'],
  ['Biznes-lanch: sho‘rva + ikkinchi taom + choy', 'Бизнес-ланч: суп + второе + чай'],
  ['Qozon kabob (1 porsiya)', 'Казан-кабоб (1 порция)'],
  ['Butun tandir tovuq + non', 'Целая курица из тандыра + лепёшка'],
  ['Dimlama (2 kishilik)', 'Димлама (на двоих)'],
  ['Uy chuchvarasi + qaymoq', 'Домашняя чучвара + каймак'],
  ['Pitsa 30 sm + 1 l ichimlik', 'Пицца 30 см + напиток 1 л'],
  ['Burger kombo: burger + fri + ichimlik', 'Бургер-комбо: бургер + фри + напиток'],
  ['Sushi set (24 dona)', 'Суши-сет (24 шт.)'],
  ['Mastava + non', 'Мастава + лепёшка'],
  ['Norin (katta porsiya)', 'Норин (большая порция)'],
  ['Samarqand oshi + Samarqand noni', 'Самаркандский плов + самаркандская лепёшка'],
  ['Buxorocha oshi sofi', 'Бухарский оши софи'],
  ['Andijoncha devzira oshi', 'Андижанский плов из девзиры'],
  ['Farg‘ona oshi + achchiq-chuchuk', 'Ферганский плов + ачик-чучук'],
  ['Jigar va qiyma kabob seti', 'Сет: кабоб из печени и люля-кабоб'],
  ['Jizzax somsasi (2 dona) + choy', 'Джизакская самса (2 шт.) + чай'],
  ['Tandir go‘sht (500 g) + non', 'Тандыр-гушт (500 г) + лепёшка'],
  ['Tuxum barak (10 dona) + choy', 'Тухум-барак (10 шт.) + чай'],
  ['Shivit oshi', 'Шивит оши'],
  ['Qoraqalpoqcha beshbarmoq', 'Бешбармак по-каракалпакски'],
  // Coffee and sweets.
  ['Kapuchino + kruassan', 'Капучино + круассан'],
  ['Ikkita latte — do‘stingiz bilan', 'Два латте — с другом'],
  ['Chizkeyk + amerikano', 'Чизкейк + американо'],
  ['Butun tort (1 kg) kechki narxda', 'Целый торт (1 кг) по вечерней цене'],
  ['Kechki desert seti: 2 desert + 2 choy', 'Вечерний десертный сет: 2 десерта + 2 чая'],
  ['Bugungi pishiriqlar qutisi (6 dona)', 'Коробка сегодняшней выпечки (6 шт.)'],
  ['Milksheyk + vafli', 'Милкшейк + вафли'],
  ['Nonushta: omlet, salat, non va kofe', 'Завтрак: омлет, салат, хлеб и кофе'],
  ['3 shar muzqaymoq', '3 шарика мороженого'],
  ['Choy seti: ko‘k choy, navvot, holva', 'Чайный сет: зелёный чай, навват, халва'],
  ['Samarqand noni (3 dona) + choy', 'Самаркандские лепёшки (3 шт.) + чай'],
  ['Buxoro shirinliklari to‘plami', 'Набор бухарских сладостей'],
  ['Qo‘qon halvosi (1 kg)', 'Кокандская халва (1 кг)'],
  // Shopping.
  ['Biznes kitoblar to‘plami (3 kitob)', 'Набор книг о бизнесе (3 книги)'],
  ['Bolalar ertaklari to‘plami (5 kitob)', 'Набор детских сказок (5 книг)'],
  ['Erkaklar klassik ko‘ylagi', 'Мужская классическая рубашка'],
  ['Ipak ro‘mol', 'Шёлковый платок'],
  ['Guldasta: 15 ta atirgul', 'Букет: 15 роз'],
  ['G‘ilof + himoya oynasi', 'Чехол + защитное стекло'],
  ['Quruq mevalar sovg‘a qutisi (1 kg)', 'Подарочная коробка сухофруктов (1 кг)'],
  ['Maktab ryukzagi', 'Школьный рюкзак'],
  ['Oila savati: yog‘, un, guruch, shakar', 'Семейная корзина: масло, мука, рис, сахар'],
  ['Sport krossovkasi', 'Спортивные кроссовки'],
  ['Oshxona idishlari to‘plami', 'Набор кухонной посуды'],
  ['Milliy libosdagi qo‘g‘irchoq', 'Кукла в национальном костюме'],
  ['Buxoro so‘zanasi (kichik)', 'Бухарское сюзане (малое)'],
  ['Rishton kosalari (6 dona)', 'Риштанские чаши (6 шт.)'],
  ['Chust do‘ppisi', 'Чустская тюбетейка'],
  ['Marg‘ilon atlasi (3 metr)', 'Маргиланский атлас (3 метра)'],
  ['Xiva yog‘och o‘ymakorligi: laux', 'Хивинская резьба по дереву: лаух'],
  ['Qoraqalpoq sovg‘alar to‘plami', 'Набор каракалпакских сувениров'],
  ['Satin choyshab to‘plami (2 kishilik)', 'Комплект постельного белья из сатина (двуспальный)'],
  ['Kelin sepi to‘plami: choyshab va sochiqlar', 'Набор в приданое: постельное бельё и полотенца'],
  ['Bolalar choyshab to‘plami (1,5 kishilik)', 'Детский комплект постельного белья (полуторный)'],
  ['Mahra sochiqlar to‘plami (6 dona)', 'Набор махровых полотенец (6 шт.)'],
  ['Hammom xalati + katta sochiq (sovg‘a qutisida)', 'Банный халат + большое полотенце (в подарочной коробке)'],
  ['Smartfon 256 GB — pushti yoki lavanda rangda', 'Смартфон 256 ГБ — розовый или лавандовый'],
  ['Smartfon sovg‘a to‘plami: g‘ilof va quvvatlagich bilan', 'Смартфон в подарочном наборе: с чехлом и зарядкой'],
  // Beauty.
  ['Gel-lak manikyur', 'Маникюр с гель-лаком'],
  ['Manikyur + pedikyur', 'Маникюр + педикюр'],
  ['Erkaklar soch turmagi', 'Мужская стрижка'],
  ['Soch turmagi + soqolni shakllantirish', 'Стрижка + оформление бороды'],
  ['Soch kesish + ukladka', 'Стрижка + укладка'],
  ['Yuzni kompleks tozalash', 'Комплексная чистка лица'],
  ['Klassik massaj (60 daqiqa)', 'Классический массаж (60 минут)'],
  ['Kipriklarni uzaytirish (klassik)', 'Наращивание ресниц (классика)'],
  ['Qosh dizayni + bo‘yash', 'Дизайн бровей + окрашивание'],
  ['Soch bo‘yash (bir tusda)', 'Окрашивание волос (в один тон)'],
  // Sport.
  ['Trenajyor zaliga bir martalik tashrif', 'Разовое посещение тренажёрного зала'],
  ['Oylik abonement (cheksiz)', 'Абонемент на месяц (безлимит)'],
  ['Basseyn: 1 tashrif (90 daqiqa)', 'Бассейн: 1 посещение (90 минут)'],
  ['Yoga darsi (guruhda)', 'Занятие йогой (в группе)'],
  ['Mini-futbol maydoni (1 soat)', 'Поле для мини-футбола (1 час)'],
  ['Boks: sinov darsi', 'Бокс: пробное занятие'],
  ['Tennis korti (1 soat)', 'Теннисный корт (1 час)'],
  ['Shaxsiy murabbiy bilan mashg‘ulot', 'Тренировка с персональным тренером'],
  ['Bolalar sport seksiyasi (1 oy)', 'Детская спортивная секция (1 месяц)'],
  ['Kurash: sinov darsi', 'Кураш: пробное занятие'],
  // Fun.
  ['Kino: 2 ta chipta', 'Кино: 2 билета'],
  ['Bouling: 1 soat, 1 yo‘lak', 'Боулинг: 1 час, 1 дорожка'],
  ['Kvest xonasi (4 kishigacha)', 'Квест-комната (до 4 человек)'],
  ['Bolalar o‘yin markazi (2 soat)', 'Детский игровой центр (2 часа)'],
  ['Karaoke xona (1 soat)', 'Караоке-комната (1 час)'],
  ['PlayStation 5 klub (2 soat)', 'Клуб PlayStation 5 (2 часа)'],
  ['Batut markazi (1 soat)', 'Батутный центр (1 час)'],
  ['Bilyard: 1 soat', 'Бильярд: 1 час'],
  ['Teatr chiptasi', 'Билет в театр'],
  ['Ot minish (30 daqiqa)', 'Катание на лошади (30 минут)'],
  // Services.
  ['Kompleks avtoyuvish (ichki + tashqi)', 'Комплексная мойка авто (салон + кузов)'],
  ['Kostyumni kimyoviy tozalash', 'Химчистка костюма'],
  ['Noutbuk profilaktikasi va tozalash', 'Профилактика и чистка ноутбука'],
  ['Poyabzal ta’miri va tozalash', 'Ремонт и чистка обуви'],
  ['Kiyim tikish va ta’mirlash', 'Пошив и ремонт одежды'],
  ['Uyni tozalash (2 xonali)', 'Уборка квартиры (2 комнаты)'],
  ['Konditsionerni tozalash va gaz tekshiruvi', 'Чистка кондиционера и проверка фреона'],
  ['Studiyada fotosessiya (30 daqiqa)', 'Фотосессия в студии (30 минут)'],
  ['Shinalarni almashtirish (4 ta)', 'Шиномонтаж (4 колеса)'],
  ['Ingliz tili: 1 oylik kurs', 'Английский язык: курс на 1 месяц'],
  ['Kompyuter savodxonligi kursi (1 oy)', 'Курс компьютерной грамотности (1 месяц)'],
  // Delivery.
  ['Osh yetkazib berish (2 porsiya)', 'Доставка плова (2 порции)'],
  ['Pitsa 35 sm + ichimlik yetkazish', 'Доставка: пицца 35 см + напиток'],
  ['Ikkita lavash + fri', 'Два лаваша + фри'],
  ['Oilaviy set (4 kishi)', 'Семейный сет (на 4 человек)'],
  ['Sushi set (32 dona) yetkazish', 'Доставка суши-сета (32 шт.)'],
  ['10 ta somsa yetkazish', 'Доставка 10 самс'],
  ['Mevalar savati (5 kg)', 'Корзина фруктов (5 кг)'],
  ['Gul yetkazish: 11 ta atirgul', 'Доставка цветов: 11 роз'],
  ['Ichimlik suvi: 2 ta 19 l', 'Питьевая вода: 2 бутыли по 19 л'],
  ['Achchiq qanotchalar (24 dona)', 'Острые крылышки (24 шт.)'],
];

const DESCRIPTIONS: Array<[string, string]> = [
  // Showcase businesses (db/seed.ts).
  ['Bir porsiya to‘y oshi, achchiq-chuchuk salat va issiq non.', 'Порция свадебного плова, салат ачик-чучук и горячая лепёшка.'],
  ['Bugun pishirilgan butun tortlar (1 kg) — kechki maxsus narx.', 'Целые торты (1 кг), испечённые сегодня, — специальная вечерняя цена.'],
  ['Uchta mashhur biznes kitobi bitta jamlanmada.', 'Три популярные книги о бизнесе в одном наборе.'],
  ['Issiq lag‘mon va yangi sabzavotli salat.', 'Горячий лагман и салат из свежих овощей.'],
  ['Katta kapuchino yoki latte va yangi pishgan kruassan.', 'Большой капучино или латте и свежий круассан.'],
  ['Ikki desert va ikki choy — do‘stlar bilan kechki uchrashuv uchun.', 'Два десерта и два чая — для вечерней встречи с друзьями.'],
  ['Klassik manikyur va gel-lak qoplama.', 'Классический маникюр и покрытие гель-лаком.'],
  ['Trenajyor zali va dush — bir martalik tashrif.', 'Тренажёрный зал и душ — разовое посещение.'],
  ['To‘rt kishilik palov, salatlar va issiq non.', 'Плов на четверых, салаты и горячая лепёшка.'],
  // Food.
  ['Bir porsiya to‘y oshi, achchiq-chuchuk salat va issiq tandir non.', 'Порция свадебного плова, салат ачик-чучук и горячая тандырная лепёшка.'],
  ['Katta porsiya lag‘mon, ko‘k choy va non.', 'Большая порция лагмана, зелёный чай и лепёшка.'],
  ['Mol go‘shtidan besh six shashlik, tandir non va sirkali piyoz.', 'Пять шампуров шашлыка из говядины, тандырная лепёшка и маринованный лук.'],
  ['Qo‘y go‘shti va piyozli yirik manti, qatiq bilan.', 'Крупные манты с бараниной и луком, с катыком.'],
  ['Go‘shtli tandir somsa, tandirdan yangi uzilgan.', 'Тандырная самса с мясом, только из тандыра.'],
  ['Kunning sho‘rvasi, ikkinchi taom, salat va choy.', 'Суп дня, второе блюдо, салат и чай.'],
  ['Qozonda qovurilgan go‘sht va kartoshka, ko‘kat bilan.', 'Мясо с картофелем, обжаренные в казане, с зеленью.'],
  ['Tandirda pishgan butun tovuq, 2–3 kishiga yetadi.', 'Целая курица из тандыра, хватит на 2–3 человек.'],
  ['Go‘sht, kartoshka, karam va sabzavotlardan dimlama.', 'Димлама из мяса, картофеля, капусты и овощей.'],
  ['Qo‘lda tugilgan chuchvara, qaymoq va ko‘kat bilan.', 'Чучвара ручной лепки, с каймаком и зеленью.'],
  ['Istalgan klassik pitsa va bir litrli ichimlik.', 'Любая классическая пицца и напиток 1 л.'],
  ['Mol go‘shtli burger, kartoshka fri va ichimlik.', 'Бургер с говядиной, картофель фри и напиток.'],
  ['Filadelfiya, Kaliforniya va maki rollari aralash seti.', 'Сет из роллов «Филадельфия», «Калифорния» и маки.'],
  ['Guruchli issiq mastava, qatiq va ko‘kat bilan.', 'Горячая мастава с рисом, катыком и зеленью.'],
  ['Qo‘lda to‘g‘ralgan xamir va qazi, sho‘rva bilan.', 'Тесто и казы, нарезанные вручную, с бульоном.'],
  ['Sariq sabzi bilan damlangan Samarqand oshi va mashhur Samarqand noni.', 'Самаркандский плов с жёлтой морковью и знаменитая самаркандская лепёшка.'],
  ['Buxoro uslubida, zira va mayizli bayram oshi.', 'Праздничный плов по-бухарски, с зирой и изюмом.'],
  ['Devzira guruchidan, qazi va bedana tuxumi bilan.', 'Из риса девзира, с казы и перепелиными яйцами.'],
  ['Vodiy uslubidagi osh, yangi salat bilan.', 'Плов по-ферганскому рецепту, со свежим салатом.'],
  ['Namangancha jigar kabob, qiyma kabob va tandir non.', 'Наманганский кабоб из печени, люля-кабоб и тандырная лепёшка.'],
  ['Mashhur katta Jizzax somsasi, tandirdan yangi uzilgan.', 'Знаменитая большая джизакская самса, только из тандыра.'],
  ['Archa shoxida dimlangan tandir go‘sht, issiq non bilan.', 'Тандыр-гушт, томлённый на ветках арчи, с горячей лепёшкой.'],
  ['Xorazmcha tuxum barak, sariyog‘ bilan.', 'Хорезмский тухум-барак со сливочным маслом.'],
  ['Ukropli yashil xamirdan Xorazm oshi, qatiq bilan.', 'Хорезмская лапша из зелёного теста с укропом, с катыком.'],
  ['Qaynatilgan go‘sht, yupqa xamir va sho‘rva.', 'Отварное мясо, тонкое тесто и бульон.'],
  // Coffee and sweets.
  ['Katta kapuchino va sariyog‘li kruassan.', 'Большой капучино и круассан на сливочном масле.'],
  ['Ikkita latte, istalgan sirop bilan.', 'Два латте с любым сиропом.'],
  ['San-Sebastyan chizkeyki va amerikano.', 'Чизкейк «Сан-Себастьян» и американо.'],
  ['Bugun pishirilgan tortlardan istalgani.', 'Любой из тортов, испечённых сегодня.'],
  ['Ikki desert va ikki choy — kechki suhbat uchun.', 'Два десерта и два чая — для вечерней беседы.'],
  ['Kun oxirida qolgan yangi pishiriqlar — isrof bo‘lmasin.', 'Свежая выпечка, оставшаяся к концу дня, — чтобы ничего не пропало.'],
  ['Qulupnayli yoki shokoladli milksheyk va Belgiya vaflisi.', 'Клубничный или шоколадный милкшейк и бельгийские вафли.'],
  ['To‘yimli nonushta soat 11:00 gacha.', 'Сытный завтрак до 11:00.'],
  ['Uyda tayyorlangan muzqaymoq, uchta ta’m.', 'Мороженое собственного приготовления, три вкуса.'],
  ['Choynakda ko‘k choy, navvot va uy holvasi.', 'Зелёный чай в чайнике, навват и домашняя халва.'],
  ['Tandirdan yangi uzilgan mashhur Samarqand noni.', 'Знаменитая самаркандская лепёшка прямо из тандыра.'],
  ['Navvot, pashmak va yong‘oqli holva — 1 kg.', 'Навват, пашмак и халва с орехами — 1 кг.'],
  ['Qo‘lda tortilgan mashhur Qo‘qon halvosi.', 'Знаменитая кокандская халва ручной тяжки.'],
  // Shopping.
  ['O‘zbek tilidagi uchta mashhur biznes kitobi.', 'Три популярные книги о бизнесе на узбекском языке.'],
  ['Rasmli ertak kitoblari, 3–8 yosh uchun.', 'Книги сказок с картинками, для детей 3–8 лет.'],
  ['Paxta matodan klassik ko‘ylak, barcha o‘lchamlar.', 'Классическая рубашка из хлопка, все размеры.'],
  ['Tabiiy ipakdan milliy naqshli ro‘mol.', 'Платок из натурального шёлка с национальным узором.'],
  ['Yangi uzilgan atirgullar, chiroyli o‘ram bilan.', 'Свежесрезанные розы в красивой упаковке.'],
  ['Telefoningiz uchun g‘ilof va himoya oynasi, o‘rnatib beramiz.', 'Чехол и защитное стекло для вашего телефона — установим сами.'],
  ['Mayiz, o‘rik, yong‘oq va bodom — sovg‘a qutisida.', 'Изюм, урюк, грецкий орех и миндаль — в подарочной коробке.'],
  ['Ortopedik orqa qismli, yengil maktab ryukzagi.', 'Лёгкий школьный рюкзак с ортопедической спинкой.'],
  ['Kundalik mahsulotlar to‘plami — bir haftaga yetadi.', 'Набор продуктов на каждый день — хватит на неделю.'],
  ['Yengil va qulay krossovka, 36–45 o‘lchamlar.', 'Лёгкие и удобные кроссовки, размеры 36–45.'],
  ['Qopqoqli kastryulkalar va tova to‘plami.', 'Набор кастрюль с крышками и сковорода.'],
  ['Konigil hunarmandlari qo‘lda yasagan, naqshli to‘nli qo‘g‘irchoq.', 'Кукла в узорчатом чапане, сделанная вручную мастерами Конигила.'],
  ['Qo‘lda tikilgan so‘zana, 60×60 sm.', 'Сюзане ручной вышивки, 60×60 см.'],
  ['Ishqorli sirda qo‘lda chizilgan kosalar to‘plami.', 'Набор чаш с ручной росписью под щелочной глазурью.'],
  ['Oq-qora naqshli klassik Chust do‘ppisi.', 'Классическая чустская тюбетейка с чёрно-белым узором.'],
  ['Qo‘lda to‘qilgan tabiiy ipak atlas.', 'Атлас из натурального шёлка ручного ткачества.'],
  ['Kitob uchun o‘yma yog‘och laux — xivalik ustadan.', 'Резная деревянная подставка для книги (лаух) — от хивинского мастера.'],
  ['Kashta tikilgan sumka, magnit va milliy bezaklar.', 'Сумка с вышивкой, магнит и национальные украшения.'],
  ['Yumshoq satin, pastel ranglarda: ko‘rpa jildi, choyshab va ikkita yostiq jildi.', 'Мягкий сатин пастельных оттенков: пододеяльник, простыня и две наволочки.'],
  ['Sovg‘a qutisida: ikki kishilik choyshab to‘plami, to‘rtta mahra sochiq va hammom xalati.', 'В подарочной коробке: двуспальный комплект белья, четыре махровых полотенца и банный халат.'],
  ['Rasmli, 100% paxta: ko‘rpa jildi, choyshab va yostiq jildi. Yuvilganda rangi o‘chmaydi.', 'С рисунком, 100% хлопок: пододеяльник, простыня и наволочка. Не линяет при стирке.'],
  ['Yuz, qo‘l va hammom uchun: 100% paxta, yumshoq va suvni yaxshi shimadi.', 'Для лица, рук и ванной: 100% хлопок, мягкие и хорошо впитывают воду.'],
  ['Yumshoq mahra xalat va katta sochiq — onangiz yoki opa-singlingizga yoqimli sovg‘a.', 'Мягкий махровый халат и большое полотенце — приятный подарок маме или сестре.'],
  ['6,7 dyuymli ekran, 50 MP kamera va 5000 mAh batareya. Rasmiy kafolat — 1 yil.', 'Экран 6,7 дюйма, камера 50 Мп и аккумулятор 5000 мА·ч. Официальная гарантия — 1 год.'],
  ['128 GB smartfon, chiroyli g‘ilof, himoya oynasi va tez quvvatlagich — sovg‘a qutisida.', 'Смартфон на 128 ГБ, красивый чехол, защитное стекло и быстрая зарядка — в подарочной коробке.'],
  // Beauty.
  ['Apparat manikyur va gel-lak qoplama.', 'Аппаратный маникюр и покрытие гель-лаком.'],
  ['Klassik manikyur va pedikyur, gel-lak bilan.', 'Классический маникюр и педикюр с гель-лаком.'],
  ['Soch turmagi, yuvish va ukladka.', 'Стрижка, мытьё головы и укладка.'],
  ['Barber xizmati: soch va soqol, issiq sochiq bilan.', 'Барбер: стрижка и борода, с горячим полотенцем.'],
  ['Ayollar soch turmagi va fen bilan ukladka.', 'Женская стрижка и укладка феном.'],
  ['Kosmetolog tomonidan tozalash va niqob.', 'Чистка у косметолога и маска.'],
  ['Butun tana massaji, tajribali mutaxassis.', 'Массаж всего тела, опытный специалист.'],
  ['Klassik usulda kiprik uzaytirish.', 'Наращивание ресниц классическим методом.'],
  ['Qosh shaklini to‘g‘rilash va bo‘yash.', 'Коррекция формы бровей и окрашивание.'],
  ['Professional bo‘yoq, o‘rta uzunlikdagi soch.', 'Профессиональная краска, волосы средней длины.'],
  // Sport.
  ['Zal, kardio zona va dush — bir martalik tashrif.', 'Зал, кардиозона и душ — разовое посещение.'],
  ['Bir oy davomida cheksiz tashrif.', 'Безлимитные посещения в течение месяца.'],
  ['25 metrli basseyn, sauna va dush.', '25-метровый бассейн, сауна и душ.'],
  ['Boshlovchilar uchun guruh darsi, gilamcha beriladi.', 'Групповое занятие для начинающих, коврик выдаётся.'],
  ['Sun’iy qoplamali yopiq maydon, kiyinish xonasi bilan.', 'Крытое поле с искусственным покрытием и раздевалкой.'],
  ['Murabbiy bilan birinchi dars, qo‘lqoplar beriladi.', 'Первое занятие с тренером, перчатки выдаются.'],
  ['Yopiq kort, raketkalar ijarasi mumkin.', 'Крытый корт, можно взять ракетки напрокат.'],
  ['Bir soatlik individual mashg‘ulot va reja.', 'Часовая индивидуальная тренировка и план занятий.'],
  ['Haftada uch marta, 6–14 yoshli bolalar uchun.', 'Три раза в неделю, для детей 6–14 лет.'],
  ['Milliy kurash bo‘yicha birinchi dars.', 'Первое занятие по национальной борьбе кураш.'],
  // Fun.
  ['Istalgan seansga ikki chipta.', 'Два билета на любой сеанс.'],
  ['6 kishigacha, poyabzal ijarasi bilan.', 'До 6 человек, с арендой обуви.'],
  ['60 daqiqalik sirli kvest, yoshlar va kattalar uchun.', 'Загадочный квест на 60 минут для молодёжи и взрослых.'],
  ['Labirint, batut va animatorlar.', 'Лабиринт, батут и аниматоры.'],
  ['8 kishigacha, o‘zbek va xorijiy qo‘shiqlar.', 'До 8 человек, узбекские и зарубежные песни.'],
  ['Katta ekran, ikki joystik, yangi o‘yinlar.', 'Большой экран, два джойстика, новые игры.'],
  ['Bolalar va kattalar uchun batut zali.', 'Батутный зал для детей и взрослых.'],
  ['Professional stol, kiy va sharlar beriladi. 4 kishigacha.', 'Профессиональный стол, кий и шары выдаются. До 4 человек.'],
  ['Bugungi spektaklga partere chipta.', 'Билет в партер на сегодняшний спектакль.'],
  ['Instruktor bilan sayr, boshlovchilar uchun.', 'Прогулка с инструктором, для начинающих.'],
  // Services.
  ['Kuzov, salon, gilamchalar va shisha tozalash.', 'Кузов, салон, коврики и стёкла.'],
  ['Ikki qismli kostyum, 24 soatda tayyor.', 'Костюм-двойка, готово за 24 часа.'],
  ['Changdan tozalash va termopasta almashtirish.', 'Чистка от пыли и замена термопасты.'],
  ['Taglik, tikuv va chuqur tozalash.', 'Подошва, швы и глубокая чистка.'],
  ['Qisqartirish, zamok almashtirish va tikish.', 'Укорачивание, замена молнии и пошив.'],
  ['Ikki kishilik brigada, o‘z vositalari bilan.', 'Бригада из двух человек со своими средствами.'],
  ['Ichki va tashqi blokni tozalash.', 'Чистка внутреннего и внешнего блоков.'],
  ['20 ta ishlangan surat, fon tanlash mumkin.', '20 обработанных фотографий, фон на выбор.'],
  ['Yechish, o‘rnatish va balansirovka.', 'Снятие, установка и балансировка.'],
  ['Haftada uch dars, kichik guruhlarda.', 'Три занятия в неделю, в небольших группах.'],
  ['Word, Excel va internet — noldan, amaliy mashg‘ulotlarda.', 'Word, Excel и интернет — с нуля, на практических занятиях.'],
  // Delivery.
  ['Issiq to‘y oshi, salat va non — eshigingizgacha.', 'Горячий свадебный плов, салат и лепёшка — до вашей двери.'],
  ['Katta pitsa va 1 l ichimlik, 45 daqiqada.', 'Большая пицца и напиток 1 л — за 45 минут.'],
  ['Tovuqli yoki go‘shtli lavash, fri bilan.', 'Лаваш с курицей или мясом, с картофелем фри.'],
  ['Shashlik, salatlar, non va ichimliklar.', 'Шашлык, салаты, лепёшки и напитки.'],
  ['To‘rt xil roll, soya sousi va imbir bilan.', 'Четыре вида роллов, с соевым соусом и имбирём.'],
  ['Go‘shtli tandir somsa, issiq holda.', 'Тандырная самса с мясом, горячая.'],
  ['Mavsumiy mevalar — olma, uzum, anor.', 'Сезонные фрукты — яблоки, виноград, гранаты.'],
  ['Guldasta va tabriknoma bilan.', 'Букетом, с поздравительной открыткой.'],
  ['Tozalangan ichimlik suvi, qavatgacha olib chiqamiz.', 'Очищенная питьевая вода, поднимем на этаж.'],
  ['Qarsildoq tovuq qanotchalari, ikki xil sous bilan.', 'Хрустящие куриные крылышки с двумя соусами.'],
];

const TERMS: Array<[string, string]> = [
  ['Faqat restoranda. Boshqa chegirmalar bilan qo‘shilmaydi.', 'Только в ресторане. Не суммируется с другими скидками.'],
  ['Mavjud assortimentdan. Oldindan buyurtmaga tatbiq etilmaydi.', 'Из имеющегося ассортимента. Не распространяется на предзаказ.'],
  ['Do‘kondan olib ketish. Bir mijozga bitta to‘plam.', 'Самовывоз из магазина. Один набор в одни руки.'],
  ['Choyxonada iste’mol qilish uchun. Bir mijozga bir marta.', 'Для употребления в чайхане. Один раз на клиента.'],
  ['Soat 12:00 gacha. Bir mijozga kuniga ikki marta.', 'До 12:00. Не более двух раз в день на клиента.'],
  ['Faqat kafeda. Stol band qilish shart emas.', 'Только в кафе. Бронировать стол не нужно.'],
  ['Kodni tashrif paytida ko‘rsating. Navbat bo‘lsa, vaqtni joyida kelishib olasiz.', 'Покажите код при визите. Если есть очередь, время согласуете на месте.'],
  ['Sport kiyimi va almashtiriladigan poyabzal bilan keling.', 'Приходите в спортивной одежде и со сменной обувью.'],
  ['Faqat ish kunlari. Buyurtmani kamida 2 soat oldin bering.', 'Только по будням. Сделайте заказ минимум за 2 часа.'],
  ['Joyida tanovul qilish yoki olib ketish mumkin. Kodni kassada ko‘rsating.', 'Можно поесть на месте или взять с собой. Покажите код на кассе.'],
  ['Boshqa aksiyalar bilan qo‘shilmaydi. Kodni buyurtma berishda ayting.', 'Не суммируется с другими акциями. Назовите код при заказе.'],
  ['Kodni kassada ko‘rsating. Olib ketish ham mumkin.', 'Покажите код на кассе. Можно взять с собой.'],
  ['Bugungi assortimentdan. Boshqa chegirmalar bilan qo‘shilmaydi.', 'Из сегодняшнего ассортимента. Не суммируется с другими скидками.'],
  ['Do‘kondan olib ketish. Chek bilan 3 kun ichida almashtirish mumkin.', 'Самовывоз из магазина. Обмен по чеку в течение 3 дней.'],
  ['Mahsulot tugaguncha amal qiladi. Kodni kassada ko‘rsating.', 'Действует, пока товар есть в наличии. Покажите код на кассе.'],
  ['Bir mijozga bir marta. Qo‘shimcha xizmatlar alohida to‘lanadi.', 'Один раз на клиента. Дополнительные услуги оплачиваются отдельно.'],
  ['Kodni ma’muriyatda ko‘rsating. Birinchi tashrifda hujjat so‘raladi.', 'Покажите код администратору. При первом визите попросят документ.'],
  ['Seans vaqtini kassada tanlaysiz. Dam olish kunlari ham amal qiladi.', 'Время сеанса выберете на кассе. Действует и в выходные.'],
  ['Kodni kassada ko‘rsating. Bolalar kattalar bilan kelishi kerak.', 'Покажите код на кассе. Дети — только со взрослыми.'],
  ['Kodni usta bilan uchrashuvda ko‘rsating. Ehtiyot qismlar alohida to‘lanadi.', 'Покажите код мастеру при встрече. Запчасти оплачиваются отдельно.'],
  ['Navbatni joyida olasiz. Qo‘shimcha ishlar alohida kelishiladi.', 'Очередь — на месте. Дополнительные работы согласуются отдельно.'],
  ['Buyurtma berishda kodni ayting. Shahar ichida yetkazish bepul, to‘lov kuryerga.', 'Назовите код при заказе. Доставка по городу бесплатная, оплата курьеру.'],
  ['Kodni operatorga ayting. To‘lov naqd yoki karta orqali kuryerga.', 'Назовите код оператору. Оплата курьеру наличными или картой.'],
];

/** What sets hold. */
const SET_ITEMS: Array<[string, string]> = [
  ['Kunning sho‘rvasi', 'Суп дня'],
  ['Ikkinchi taom', 'Второе блюдо'],
  ['Salat', 'Салат'],
  ['Choy', 'Чай'],
  ['Filadelfiya roll', 'Ролл «Филадельфия»'],
  ['Kaliforniya roll', 'Ролл «Калифорния»'],
  ['Maki roll', 'Маки-ролл'],
  ['Tempura roll', 'Темпура-ролл'],
  ['Shashlik (six)', 'Шашлык (шампур)'],
  ['Tandir non', 'Тандырная лепёшка'],
  ['Sirkali piyoz', 'Маринованный лук'],
  ['Ko‘k choy (choynak)', 'Зелёный чай (чайник)'],
  ['Navvot', 'Навват'],
  ['Uy holvasi', 'Домашняя халва'],
  ['Ichimlik (1 l)', 'Напиток (1 л)'],
  ['Ichimlik', 'Напиток'],
  ['Desert', 'Десерт'],
  ['Mol go‘shtli burger', 'Бургер с говядиной'],
  ['Kartoshka fri', 'Картофель фри'],
  ['Ko‘rpa jildi', 'Пододеяльник'],
  ['Choyshab', 'Простыня'],
  ['Yostiq jildi', 'Наволочка'],
  ['Choyshab to‘plami (2 kishilik)', 'Комплект белья (двуспальный)'],
  ['Mahra sochiq', 'Махровое полотенце'],
  ['Hammom sochig‘i', 'Банное полотенце'],
  ['Qo‘l sochig‘i', 'Полотенце для рук'],
  ['Yuz sochig‘i', 'Полотенце для лица'],
  ['Hammom xalati', 'Банный халат'],
  ['Katta sochiq', 'Большое полотенце'],
  ['Smartfon (128 GB)', 'Смартфон (128 ГБ)'],
  ['G‘ilof', 'Чехол'],
  ['Himoya oynasi', 'Защитное стекло'],
  ['Tez quvvatlagich', 'Быстрая зарядка'],
];

const BUSINESSES: Array<[string, string]> = [
  // Showcase businesses (db/seed.ts).
  ['Toshkent palovi, milliy taomlar va oilaviy setlar. Har kuni 10:00 dan.', 'Ташкентский плов, национальные блюда и семейные сеты. Ежедневно с 10:00.'],
  ['Har kuni yangi pishiriq, tortlar va desertlar.', 'Каждый день свежая выпечка, торты и десерты.'],
  ['Kitoblar, sovg‘alar va foydali to‘plamlar.', 'Книги, подарки и полезные наборы.'],
  ['Oilaviy choyxona, lag‘mon va tezkor tushliklar.', 'Семейная чайхана, лагман и быстрые обеды.'],
  ['Qovurilgan kofe, kruassanlar va shinam muhit.', 'Свежеобжаренный кофе, круассаны и уютная атмосфера.'],
  ['Manikyur, pedikyur va soch turmagi.', 'Маникюр, педикюр и стрижки.'],
  ['Zamonaviy trenajyorlar va guruh mashg‘ulotlari.', 'Современные тренажёры и групповые занятия.'],
  ['Yangi ochilgan burgerxona: go‘shtli va tovuqli burgerlar.', 'Недавно открывшаяся бургерная: бургеры с говядиной и курицей.'],
  // One per category, by turns.
  ['Milliy taomlar, tandir non va oilaviy muhit.', 'Национальные блюда, тандырные лепёшки и семейная атмосфера.'],
  ['Har kuni yangi pishirilgan issiq taomlar va tezkor tushliklar.', 'Каждый день свежие горячие блюда и быстрые обеды.'],
  ['Qozonda pishgan taomlar, choyxona muhiti va keng dasturxon.', 'Блюда из казана, атмосфера чайханы и щедрый дастархан.'],
  ['Qovurilgan kofe, yangi pishiriqlar va shinam muhit.', 'Свежеобжаренный кофе, свежая выпечка и уютная атмосфера.'],
  ['Tortlar, desertlar va kechki choy uchun qulay joy.', 'Торты, десерты и уютное место для вечернего чая.'],
  ['Ertalabki kofe va kechki desertlar — har kuni yangi.', 'Утренний кофе и вечерние десерты — каждый день свежие.'],
  ['Kiyim-kechak, sovg‘alar va kundalik xaridlar.', 'Одежда, подарки и покупки на каждый день.'],
  ['Oila uchun kerakli mahsulotlar bir joyda.', 'Всё нужное для семьи в одном месте.'],
  ['Manikyur, soch turmagi va parvarish xizmatlari.', 'Маникюр, стрижки и уходовые процедуры.'],
  ['Tajribali ustalar va zamonaviy parvarish vositalari.', 'Опытные мастера и современные средства ухода.'],
  ['Ayollar va erkaklar uchun go‘zallik xizmatlari.', 'Услуги красоты для женщин и мужчин.'],
  ['Zamonaviy trenajyorlar, guruh mashg‘ulotlari va dush.', 'Современные тренажёры, групповые занятия и душ.'],
  ['Kattalar va bolalar uchun sport mashg‘ulotlari.', 'Спортивные занятия для взрослых и детей.'],
  ['Tajribali murabbiylar va qulay jadval.', 'Опытные тренеры и удобное расписание.'],
  ['Oila va do‘stlar bilan dam olish uchun ko‘ngilochar markaz.', 'Развлекательный центр для отдыха с семьёй и друзьями.'],
  ['Kino, o‘yinlar va bayramlar uchun joy.', 'Место для кино, игр и праздников.'],
  ['Bolalar va kattalar uchun faol dam olish.', 'Активный отдых для детей и взрослых.'],
  ['Tez va sifatli maishiy xizmatlar.', 'Быстрые и качественные бытовые услуги.'],
  ['Avtomobil va uy uchun ishonchli xizmatlar.', 'Надёжные услуги для автомобиля и дома.'],
  ['Tajribali ustalar, kafolatli ish.', 'Опытные мастера, работа с гарантией.'],
  ['Shahar bo‘ylab tezkor yetkazib berish.', 'Быстрая доставка по городу.'],
  ['Issiq taomlarni uyingizgacha yetkazamiz.', 'Доставим горячие блюда до вашего дома.'],
  ['Buyurtma — bir soat ichida eshigingizda.', 'Заказ — у вашей двери в течение часа.'],
  // Businesses with their own description.
  ['Samarqand noni, patir va shirinliklar — tandirdan yangi.', 'Самаркандские лепёшки, патыр и сладости — прямо из тандыра.'],
  ['Milliy qo‘g‘irchoqlar, sopol va hunarmandlar sovg‘alari.', 'Национальные куклы, керамика и подарки от ремесленников.'],
  ['Navvot, pashmak, holva va ko‘k choy.', 'Навват, пашмак, халва и зелёный чай.'],
  ['So‘zana, zardo‘zi va misgarlik buyumlari.', 'Сюзане, золотое шитьё и чеканка по меди.'],
  ['Rishton ustalarining qo‘lda chizilgan sopol buyumlari.', 'Керамика с ручной росписью от риштанских мастеров.'],
  ['Toza ichimlik suvi va mevalar yetkazib berish.', 'Доставка чистой питьевой воды и фруктов.'],
  ['Chust do‘ppilari, pichoqlari va milliy sovg‘alar.', 'Чустские тюбетейки, ножи и национальные сувениры.'],
  ['Noutbuk, telefon va maishiy texnika ta’miri.', 'Ремонт ноутбуков, телефонов и бытовой техники.'],
  ['Namangan bog‘laridan meva va quruq mevalar.', 'Фрукты и сухофрукты из садов Намангана.'],
  ['Mashhur Qo‘qon halvosi va milliy shirinliklar.', 'Знаменитая кокандская халва и национальные сладости.'],
  ['Marg‘ilon atlasi va adrasi — to‘g‘ridan-to‘g‘ri ustaxonadan.', 'Маргиланский атлас и адрас — прямо из мастерской.'],
  ['Kiyim tikish, ta’mirlash va milliy liboslar.', 'Пошив и ремонт одежды, национальные костюмы.'],
  ['Yangi gullar, guldastalar va sovg‘alar.', 'Свежие цветы, букеты и подарки.'],
  ['Uy va ofislarni professional tozalash.', 'Профессиональная уборка квартир и офисов.'],
  ['Konditsioner va sovutgichlar xizmati — issiq kunlarda ham tez.', 'Обслуживание кондиционеров и холодильников — быстро даже в жару.'],
  ['Fotosessiya, hujjat uchun surat va chop etish.', 'Фотосессии, фото на документы и печать.'],
  ['Xiva ustalarining yog‘och o‘ymakorligi va sovg‘alari.', 'Резьба по дереву и сувениры хивинских мастеров.'],
  ['Qoraqalpoq kashtasi, bezaklar va sovg‘alar.', 'Каракалпакская вышивка, украшения и сувениры.'],
  ['Ot minish, bolalar maydonchasi va oilaviy dam olish.', 'Катание на лошадях, детская площадка и семейный отдых.'],
  ['Ingliz tili, kompyuter savodxonligi va tayyorlov kurslari.', 'Английский язык, компьютерная грамотность и подготовительные курсы.'],
  // Home textiles and phones (EXTRA_SHOPS).
  ['Choyshab, sochiq va uy tekstili — kelin sepi uchun to‘plamlar ham bor.', 'Постельное бельё, полотенца и домашний текстиль — есть и наборы в приданое.'],
  ['Smartfonlar, g‘iloflar va aksessuarlar — rasmiy kafolat bilan.', 'Смартфоны, чехлы и аксессуары — с официальной гарантией.'],
  ['Paxta va satin choyshablar, mahra sochiqlar va sovg‘a to‘plamlari.', 'Бельё из хлопка и сатина, махровые полотенца и подарочные наборы.'],
  ['Choyshablar, sochiqlar va hammom xalatlari — sovg‘a qutisida ham.', 'Постельное бельё, полотенца и банные халаты — в том числе в подарочной коробке.'],
  ['Kattalar va bolalar uchun paxta choyshablar, yumshoq sochiqlar.', 'Хлопковое бельё для взрослых и детей, мягкие полотенца.'],
  ['Smartfonlar va aksessuarlar — telefonni sozlab beramiz.', 'Смартфоны и аксессуары — настроим телефон за вас.'],
  ['Yangi smartfonlar, g‘iloflar va himoya oynalari.', 'Новые смартфоны, чехлы и защитные стёкла.'],
];

const BRANCHES: Array<[string, string]> = [
  ['Asosiy filial', 'Основной филиал'],
  ['Markaziy filial', 'Центральный филиал'],
  ['Markaz', 'Центр'],
  ['Yunusobod filiali', 'Филиал в Юнусабаде'],
  ['Chilonzor filiali', 'Филиал в Чиланзаре'],
  ['Mirzo Ulug‘bek filiali', 'Филиал в Мирзо-Улугбеке'],
  ['Yakkasaroy filiali', 'Филиал в Яккасарае'],
  ['Shayxontohur filiali', 'Филиал в Шайхантахуре'],
  ['Mirobod filiali', 'Филиал в Мирабаде'],
  ['Olmazor filiali', 'Филиал в Алмазаре'],
  ['Sergeli filiali', 'Филиал в Сергели'],
  ['Chilonzor 19-kvartal', 'Чиланзар, 19-й квартал'],
  ['Samarqand Darvoza', 'Самарканд-Дарвоза'],
  ['Anhor filiali', 'Филиал на Анхоре'],
  ['Registon', 'Регистан'],
  ['Bobur shoh ko‘chasi', 'Улица Бобуршох'],
];

export const SAMPLE_RU: ReadonlyMap<string, string> = new Map([...TITLES, ...DESCRIPTIONS, ...TERMS, ...SET_ITEMS, ...BUSINESSES, ...BRANCHES]);

/** A sample's text for the Russian site; a text that is not in the catalogue stays as it is. */
export function sampleInRussian(text: string) {
  return SAMPLE_RU.get(text) ?? text;
}
