import type { Metadata } from 'next';
import { ArrowRight, BadgeCheck, BarChart3, Building2, Users } from 'lucide-react';

import { buttonVariants } from '@/components/ui/button';
import { cn } from '@/lib/utils';

export const metadata: Metadata = { title: 'Biznes uchun', description: 'Bo‘sh joy va cheklangan mahsulotni BugunBor orqali yangi mijozlarga aylantiring.', alternates: { canonical: '/business' } };

export default function BusinessPage() {
  return <main className="min-h-screen bg-[#152a3b] text-white"><header className="border-b border-white/10"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><a href="/" className="text-xl font-black">Bugun<span className="text-orange-400">Bor</span></a><a href="/business/dashboard" className="text-sm font-bold text-slate-300">Dashboard</a></div></header><section className="mx-auto grid max-w-6xl items-center gap-12 px-4 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-bold uppercase tracking-[.15em] text-orange-300">BugunBor Business</p><h1 className="mt-4 text-5xl font-black leading-[.98] tracking-[-.06em] sm:text-6xl">Bugungi imkoniyatni yangi mijozga aylantiring.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Cheklangan aksiya yarating, moderatsiyadan o‘ting va filiallar bo‘yicha natijani real vaqtda kuzating.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/business/onboarding" className={cn(buttonVariants(), 'h-12 rounded-xl bg-orange-500 px-6 font-bold text-white hover:bg-orange-400')}>Bepul boshlash <ArrowRight className="ml-2 size-4" /></a><a href="/business/dashboard" className={cn(buttonVariants({ variant: 'outline' }), 'h-12 rounded-xl border-white/20 bg-white/5 px-6 text-white hover:bg-white/10')}>Demo dashboard</a></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-3xl bg-white p-6 text-[#152a3b]"><Building2 className="size-7 text-orange-500" /><strong className="mt-8 block text-4xl font-black">4</strong><span className="text-sm text-slate-500">filialgacha START rejada</span></div><div className="rounded-3xl bg-orange-500 p-6"><BarChart3 className="size-7" /><strong className="mt-8 block text-4xl font-black">Real time</strong><span className="text-sm text-orange-100">ko‘rish va conversion</span></div><div className="rounded-3xl bg-white/8 p-6"><BadgeCheck className="size-7 text-emerald-300" /><strong className="mt-8 block text-2xl font-black">Verified</strong><span className="text-sm text-slate-300">ishonch belgisi</span></div><div className="rounded-3xl bg-white/8 p-6"><Users className="size-7 text-sky-300" /><strong className="mt-8 block text-2xl font-black">Jamoa</strong><span className="text-sm text-slate-300">aniq ruxsatlar bilan</span></div></div></section></main>;
}
